services:
  - type: web
    name: interactive-dictionary
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MISTRAL_API_KEY
        sync: false
      - key: FLASK_DEBUG
        value: False
      - key: PORT
        fromService:
          type: web
          name: interactive-dictionary
          property: port
